### ISSUE TITLE
Actionlib-msgs is in lib/python3.7/site-packages

### ISSUE THREAD

**Issue by orestiskapar** [ros-melodic-arch/ros-melodic-actionlib-msgs#1] opened 2020-03-22 15:00 UTC
Not sure if this is the correct repo for this but:
`actionlib-msgs` is placed in `/opt/melodic/lib/python3.7/site-packages` while `actionlib` and `actionlib-tutorials` are in `/opt/melodic/lib/python3.8/site-packages`.

`roslaunch` was failing because of ModuleNotFoundError for `actionlib-msgs`. Copying `actionlib-msgs` over to `/opt/melodic/lib/python3.8/site-packages` seems to work but it does not look like a good solution.

**Comment by jwhendy** [comment] 2020-03-22 18:06
That's peculiar. I just rebuilt from scratch ~1 week ago and don't observe this.

```
$ pacman -Q | grep actionlib
ros-melodic-actionlib 1.12.0-3
ros-melodic-actionlib-msgs 1.12.7-2
ros-melodic-actionlib-tutorials 0.1.11-3
ros-melodic-turtle-actionlib 0.1.11-3
```

```
# I have no python3.7 folder
$ find /opt/ros/melodic/lib/ -iname python*
/opt/ros/melodic/lib/pkgconfig/python_qt_binding.pc
/opt/ros/melodic/lib/python3.8
/opt/ros/melodic/lib/python3.8/site-packages/python_qt_binding
/opt/ros/melodic/lib/python3.8/site-packages/python_qt_binding-0.3.6-py3.8.egg-info
```

Can you do a `pacman -Qo` on something in the `python3.7` directory? I'm wondering if you just have a spillover from pre-python3.8 that hasn't been properly updated.

**Comment by orestiskapar** [comment] 2020-03-22 19:02
Here are the outputs of the commands:
```zsh
➜  ~ pacman -Q | grep actionlib
ros-melodic-actionlib 1.12.0-3
ros-melodic-actionlib-msgs 1.12.7-2
ros-melodic-actionlib-tutorials 0.1.11-3
ros-melodic-turtle-actionlib 0.1.11-3
```
```zsh
➜  ~ find /opt/ros/melodic/lib/ -iname "python*"
/opt/ros/melodic/lib/python3.8
/opt/ros/melodic/lib/python3.8/site-packages/python_qt_binding-0.3.6-py3.8.egg-info
/opt/ros/melodic/lib/python3.8/site-packages/python_qt_binding
/opt/ros/melodic/lib/python3.7
/opt/ros/melodic/lib/pkgconfig/python_qt_binding.pc
```
```zsh
➜  ~ pacman -Qo /opt/ros/melodic/lib/python3.7 
/opt/ros/melodic/lib/python3.7/ is owned by ros-melodic-actionlib-msgs 1.12.7-2
/opt/ros/melodic/lib/python3.7/ is owned by ros-melodic-angles 1.9.11-2
➜  ~ pacman -Qo /opt/ros/melodic/lib/python3.7/site-packages/*     
/opt/ros/melodic/lib/python3.7/site-packages/actionlib_msgs/ is owned by ros-melodic-actionlib-msgs 1.12.7-2
/opt/ros/melodic/lib/python3.7/site-packages/angles/ is owned by ros-melodic-angles 1.9.11-2
/opt/ros/melodic/lib/python3.7/site-packages/angles-1.9.11-py3.7.egg-info is owned by ros-melodic-angles 1.9.11-2
```

**Comment by jwhendy** [comment] 2020-03-22 22:38
Super interesting. Could you elaborate on how you build/install (and maybe how you originally built/installed)? Since `python3.8` is somewhat old-news on arch, I'm guessing something isn't being triggered properly on your system.

If you're using `yay` or similar, please remove these packages, remove them from cache, and rebuild. 

Out of curiosity, do you have `python3.7` installed in parallel?

**Comment by orestiskapar** [comment] 2020-03-22 23:09
I built everything with yay, installing `ros-melodic-desktop-full` and others. After that, I found out about the `arch4edu` so I removed everything and reinstalled them (some coming from `arch4edu` this time). **Edit:** Wow, I'm terribly sorry, looks like `ros-melodic-actionlib-msgs` is also [there](https://github.com/arch4edu/arch4edu/blob/master/ros-melodic-actionlib-msgs/PKGBUILD) so it could actually be them?

I will try to rebuild soon. I don't have `python3.7` installed. I had it some time ago but I guess it updated to 3.8 at some point.
These lines that @acxz changed reference `python3.7`. Could this somehow cause it? 
https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/blob/master/PKGBUILD#L56-L58

**Comment by jwhendy** [comment] 2020-03-22 23:29
I don't think those lines are the fix. I commented about that [here](https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/pull/2#issuecomment-602288287) on the issue. A script from a previous maintainer applied that to all packages in this repo, but they aren't used by many. That comment links to an issue @acxz created a while ago that awesomely tracked down what we believed to be the only packages affected.

This isn't one of them, so I think those lines were irrelevant. Also, they would have been in my package and my libs still ended up in python3.8...

**Comment by jwhendy** [comment] 2020-03-22 23:33
Also, the way things are built/updated is not intuitive to me. Sometimes I think there are some really low-level deps that get some lib path linked and then many packages that don't actually depend on this try to link at run time, finding an error.

I still don't understand why it's not finding `std_msgs`. Can you try `import std_msgs` from a python prompt directly?

**Comment by orestiskapar** [comment] 2020-03-22 23:42
`std_msgs` did install in the correct location.
```
➜  ~ python
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import std_msgs
>>> std_msgs
<module 'std_msgs' from '/opt/ros/melodic/lib/python3.8/site-packages/std_msgs/__init__.py'>
```
#### Reinstall from AUR
Disabling `arch4edu` and installing from AUR placed `actionlib_msgs` to the correct location, in `/opt/ros/melodic/lib/python3.8/site-packages`.

**Edit:** The same for `ros-melodic-angles`, which [previously](https://github.com/ros-melodic-arch/ros-melodic-actionlib-msgs/issues/1#issuecomment-602255999) also appeared under `python3.7`.
 Now `ros-melodic-std-msgs-0.5.12-1` (notice version) from [here](https://github.com/ros-melodic-arch/ros-melodic-std-msgs/issues/1) also has no problem.

Well, I'm officially lost. Maybe best stick to the AUR?

**Comment by acxz** [comment] 2020-03-23 03:03
Yeah arch4edu usually lags behind on their syncs, although for those packages I would assume they would be caught up by now. Can we go ahead and close this issue then?

**Comment by acxz** [comment] 2020-03-23 03:07
If u could do the following @KomaGR https://github.com/arch4edu/arch4edu/wiki/Mark-a-package-OUT_OF_DATE
that would be much appreciated. Both for us and for further ArchLinux ROS users.

**Comment by bionade24** [comment] 2020-03-23 08:59
@KomaGR Use my Repo and reinstall from there.

**Comment by orestiskapar** [comment] 2020-03-23 13:04
> If u could do the following @KomaGR https://github.com/arch4edu/arch4edu/wiki/Mark-a-package-OUT_OF_DATE
> that would be much appreciated. Both for us and for further ArchLinux ROS users.

I will do that but it's not out of date, though, is it?. Isn't that what's strange in all this? 
But installing `ros-melodic-actionlib-msgs` and `ros-melodic-angles` from there consistently places them in a `python3.7` directory. It creates the directory if it doesn't exist and even deletes it if I uninstall both.

From the list of `ros-melodic-*` packages in `arch4edu` only `angles` and `actionlib-msgs` demonstrate this behaviour.

@bionade24 Is the key [here](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#oscloud) not the correct one or not up to date? I'm getting invalid signature in the packages.

**Comment by bionade24** [comment] 2020-03-23 13:49
> @bionade24 Is the key [here](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#oscloud) not the correct one or not up to date? I'm getting invalid signature in the packages.

Sorry, I added a mail in between and my fingerprint changed, you only trusted a subkey. You now have to sign `CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC`

**Closed as completed** 2020-03-23 18:13 UTC

**Comment by jwhendy** [comment] 2020-03-23 18:32
`arch4edu` must be out of date themselves. I second the request to mark this out of date, and you might cite this explicitly. It would seem they haven't flagged all packages affected by python3.7 -> python3.8 to rebuild, and thus some of their bundles have the dir structure correct and others are out of date.

**Edit:** 
>I will do that but it's not out of date, though, is it?

Just to clarify, the problem is that installing from AUR or here builds from source, so *your* environment is used (including which python3.x version is appropriate). Installing pre-built packages means you're taking the structure as it appears on *their* build system. The code might be identical, but they are shipping a version built when their system was still on python3.7. Hopefully that makes sense, and I think it means the package is, indeed, out of date as they are shipping it.
